"""add document publishing

Revision ID: 1e0619445e70
Revises: 1556c63173f6
Create Date: 2026-09-14 15:53:49.143066

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1e0619445e70'
down_revision = '1556c63173f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_follows_follower_id'))
        batch_op.drop_index(batch_op.f('ix_follows_following_id'))

    op.drop_table('follows')
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comments_writing_created'))

    with op.batch_alter_table('user_follows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_user_follows_follower'))
        batch_op.drop_index(batch_op.f('idx_user_follows_following'))
        batch_op.create_index(batch_op.f('ix_user_follows_follower_id'), ['follower_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_follows_following_id'), ['following_id'], unique=False)

    with op.batch_alter_table('writing_tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_writing_tags_tag'))
        batch_op.drop_index(batch_op.f('ix_writing_tags_writing'))

    with op.batch_alter_table('writings', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.String(length=200),
               existing_nullable=False)
        batch_op.alter_column('published_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('ix_writings_author_id'))
        batch_op.drop_index(batch_op.f('ix_writings_author_status'))
        batch_op.drop_index(batch_op.f('ix_writings_language_published_at'))
        batch_op.drop_index(batch_op.f('ix_writings_status_language'))
        batch_op.create_index(batch_op.f('ix_writings_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_writings_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('writings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_writings_user_id'))
        batch_op.drop_index(batch_op.f('ix_writings_category'))
        batch_op.create_index(batch_op.f('ix_writings_status_language'), ['status', 'language'], unique=False)
        batch_op.create_index(batch_op.f('ix_writings_language_published_at'), ['language', sa.literal_column('published_at DESC')], unique=False)
        batch_op.create_index(batch_op.f('ix_writings_author_status'), ['user_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_writings_author_id'), ['user_id'], unique=False)
        batch_op.alter_column('published_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('title',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=250),
               existing_nullable=False)

    with op.batch_alter_table('writing_tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_writing_tags_writing'), ['writing_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_writing_tags_tag'), ['tag_id'], unique=False)

    with op.batch_alter_table('user_follows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_follows_following_id'))
        batch_op.drop_index(batch_op.f('ix_user_follows_follower_id'))
        batch_op.create_index(batch_op.f('idx_user_follows_following'), ['following_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_user_follows_follower'), ['follower_id'], unique=False)

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comments_writing_created'), ['writing_id', 'created_at'], unique=False)

    op.create_table('follows',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('follower_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('following_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.CheckConstraint('follower_id <> following_id', name=op.f('ck_cannot_follow_self')),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], name=op.f('follows_follower_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['following_id'], ['users.id'], name=op.f('follows_following_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('follows_pkey')),
    sa.UniqueConstraint('follower_id', 'following_id', name=op.f('uq_follow_relationship'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    with op.batch_alter_table('follows', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_follows_following_id'), ['following_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_follows_follower_id'), ['follower_id'], unique=False)

    # ### end Alembic commands ###
