"""add video trash fields

Revision ID: 2346a1dc2bc5
Revises: 466385082500
Create Date: 2026-09-23 18:39:27.899152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2346a1dc2bc5'
down_revision = '466385082500'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('previous_status', sa.String(length=20), nullable=True))
        batch_op.create_index(batch_op.f('ix_videos_deleted_at'), ['deleted_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_videos_deleted_at'))
        batch_op.drop_column('previous_status')
        batch_op.drop_column('deleted_at')

    # ### end Alembic commands ###
