"""add cover photo fields to users

Revision ID: 3fa0913d5ffb
Revises: 0cd1726c59c0
Create Date: 2026-09-22 01:38:52.169909

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3fa0913d5ffb'
down_revision = '0cd1726c59c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artworks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_artworks_deleted_at'), ['deleted_at'], unique=False)

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comments_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_deleted_at'), ['deleted_at'], unique=False)

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('ix_notifications_recipient_read_created'))
        batch_op.drop_constraint(batch_op.f('notifications_actor_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['actor_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover_photo_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('cover_photo_public_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('cover_photo_position_y', sa.Integer(), server_default='50', nullable=False))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.alter_column('password_reset_expires',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('uq_users_google_sub'), postgresql_where='(google_sub IS NOT NULL)')
        batch_op.drop_index(batch_op.f('ux_users_facebook_user_id'), postgresql_where='(facebook_user_id IS NOT NULL)')
        batch_op.create_index(batch_op.f('ix_users_facebook_user_id'), ['facebook_user_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_google_sub'), ['google_sub'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_google_sub'))
        batch_op.drop_index(batch_op.f('ix_users_facebook_user_id'))
        batch_op.create_index(batch_op.f('ux_users_facebook_user_id'), ['facebook_user_id'], unique=True, postgresql_where='(facebook_user_id IS NOT NULL)')
        batch_op.create_index(batch_op.f('uq_users_google_sub'), ['google_sub'], unique=True, postgresql_where='(google_sub IS NOT NULL)')
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
        batch_op.alter_column('password_reset_expires',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('cover_photo_position_y')
        batch_op.drop_column('cover_photo_public_id')
        batch_op.drop_column('cover_photo_url')

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('notifications_actor_id_fkey'), 'users', ['actor_id'], ['id'], ondelete='SET NULL')
        batch_op.create_index(batch_op.f('ix_notifications_recipient_read_created'), ['recipient_id', 'is_read', 'created_at'], unique=False)
        batch_op.alter_column('type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_deleted_at'))

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comments_created_at'))

    with op.batch_alter_table('artworks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_artworks_deleted_at'))

    # ### end Alembic commands ###
