"""add multilingual audio summaries

Revision ID: 466385082500
Revises: 52d38fc81be2
Create Date: 2026-09-22 19:29:43.191320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '466385082500'
down_revision = '52d38fc81be2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('writing_audio_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('writing_id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=20), nullable=False),
    sa.Column('summary_text', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), server_default='pending', nullable=False),
    sa.Column('summary_provider', sa.String(length=100), nullable=True),
    sa.Column('summary_model', sa.String(length=150), nullable=True),
    sa.Column('translation_provider', sa.String(length=100), nullable=True),
    sa.Column('translation_model', sa.String(length=150), nullable=True),
    sa.Column('tts_provider', sa.String(length=100), nullable=True),
    sa.Column('tts_model', sa.String(length=150), nullable=True),
    sa.Column('voice', sa.String(length=150), nullable=True),
    sa.Column('audio_url', sa.Text(), nullable=True),
    sa.Column('audio_public_id', sa.String(length=500), nullable=True),
    sa.Column('audio_duration_seconds', sa.Float(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['writing_id'], ['writings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('writing_id', 'language', name='uq_writing_audio_summary_language')
    )
    with op.batch_alter_table('writing_audio_summaries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_writing_audio_summaries_language'), ['language'], unique=False)
        batch_op.create_index(batch_op.f('ix_writing_audio_summaries_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_writing_audio_summaries_writing_id'), ['writing_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('writing_audio_summaries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_writing_audio_summaries_writing_id'))
        batch_op.drop_index(batch_op.f('ix_writing_audio_summaries_status'))
        batch_op.drop_index(batch_op.f('ix_writing_audio_summaries_language'))

    op.drop_table('writing_audio_summaries')
    # ### end Alembic commands ###
