"""add videos table

Revision ID: 47065e21f1b5
Revises: 3fa0913d5ffb
Create Date: 2026-09-22 15:27:38.679520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47065e21f1b5'
down_revision = '3fa0913d5ffb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('videos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('language', sa.String(length=20), nullable=False),
    sa.Column('video_url', sa.Text(), nullable=False),
    sa.Column('thumbnail_url', sa.Text(), nullable=True),
    sa.Column('public_id', sa.String(length=500), nullable=True),
    sa.Column('original_filename', sa.String(length=500), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('visibility', sa.String(length=20), nullable=False),
    sa.Column('views_count', sa.Integer(), nullable=False),
    sa.Column('likes_count', sa.Integer(), nullable=False),
    sa.Column('comments_count', sa.Integer(), nullable=False),
    sa.Column('shares_count', sa.Integer(), nullable=False),
    sa.Column('saves_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_videos_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_videos_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_videos_language'), ['language'], unique=False)
        batch_op.create_index(batch_op.f('ix_videos_public_id'), ['public_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_videos_published_at'), ['published_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_videos_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_videos_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_videos_visibility'), ['visibility'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_videos_visibility'))
        batch_op.drop_index(batch_op.f('ix_videos_user_id'))
        batch_op.drop_index(batch_op.f('ix_videos_status'))
        batch_op.drop_index(batch_op.f('ix_videos_published_at'))
        batch_op.drop_index(batch_op.f('ix_videos_public_id'))
        batch_op.drop_index(batch_op.f('ix_videos_language'))
        batch_op.drop_index(batch_op.f('ix_videos_created_at'))
        batch_op.drop_index(batch_op.f('ix_videos_category'))

    op.drop_table('videos')
    # ### end Alembic commands ###
