"""add reels system

Revision ID: 52d38fc81be2
Revises: 47065e21f1b5
Create Date: 2026-09-22 15:50:39.382680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52d38fc81be2'
down_revision = '47065e21f1b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('video_url', sa.Text(), nullable=False),
    sa.Column('thumbnail_url', sa.Text(), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=10), server_default='bn', nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('aspect_ratio', sa.String(length=20), server_default='9:16', nullable=False),
    sa.Column('visibility', sa.String(length=20), server_default='public', nullable=False),
    sa.Column('comments_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('views_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('likes_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('comments_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('shares_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('saves_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("visibility IN ('public', 'followers', 'private')", name='ck_reels_visibility'),
    sa.CheckConstraint('comments_count >= 0', name='ck_reels_comments_count'),
    sa.CheckConstraint('likes_count >= 0', name='ck_reels_likes_count'),
    sa.CheckConstraint('saves_count >= 0', name='ck_reels_saves_count'),
    sa.CheckConstraint('shares_count >= 0', name='ck_reels_shares_count'),
    sa.CheckConstraint('views_count >= 0', name='ck_reels_views_count'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reels_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_reels_language'), ['language'], unique=False)
        batch_op.create_index(batch_op.f('ix_reels_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reels_visibility'), ['visibility'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reels_visibility'))
        batch_op.drop_index(batch_op.f('ix_reels_user_id'))
        batch_op.drop_index(batch_op.f('ix_reels_language'))
        batch_op.drop_index(batch_op.f('ix_reels_created_at'))

    op.drop_table('reels')
    # ### end Alembic commands ###
